/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.adsamcik.signalcollector.map;

public class example {
  public static heatmap_t heatmap_new(long w, long h) {
    long cPtr = exampleJNI.heatmap_new(w, h);
    return (cPtr == 0) ? null : new heatmap_t(cPtr, false);
  }

  public static void heatmap_free(heatmap_t h) {
    exampleJNI.heatmap_free(heatmap_t.getCPtr(h), h);
  }

  public static void heatmap_add_point(heatmap_t h, long x, long y) {
    exampleJNI.heatmap_add_point(heatmap_t.getCPtr(h), h, x, y);
  }

  public static void heatmap_add_point_with_stamp(heatmap_t h, long x, long y, heatmap_stamp_t stamp) {
    exampleJNI.heatmap_add_point_with_stamp(heatmap_t.getCPtr(h), h, x, y, heatmap_stamp_t.getCPtr(stamp), stamp);
  }

  public static void heatmap_add_weighted_point(heatmap_t h, long x, long y, float w) {
    exampleJNI.heatmap_add_weighted_point(heatmap_t.getCPtr(h), h, x, y, w);
  }

  public static void heatmap_add_weighted_point_with_stamp(heatmap_t h, long x, long y, float w, heatmap_stamp_t stamp) {
    exampleJNI.heatmap_add_weighted_point_with_stamp(heatmap_t.getCPtr(h), h, x, y, w, heatmap_stamp_t.getCPtr(stamp), stamp);
  }

  public static SWIGTYPE_p_unsigned_char heatmap_render_default_to(heatmap_t h, SWIGTYPE_p_unsigned_char colorbuf) {
    long cPtr = exampleJNI.heatmap_render_default_to(heatmap_t.getCPtr(h), h, SWIGTYPE_p_unsigned_char.getCPtr(colorbuf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char heatmap_render_to(heatmap_t h, heatmap_colorscheme_t colorscheme, SWIGTYPE_p_unsigned_char colorbuf) {
    long cPtr = exampleJNI.heatmap_render_to(heatmap_t.getCPtr(h), h, heatmap_colorscheme_t.getCPtr(colorscheme), colorscheme, SWIGTYPE_p_unsigned_char.getCPtr(colorbuf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_unsigned_char heatmap_render_saturated_to(heatmap_t h, heatmap_colorscheme_t colorscheme, float saturation, SWIGTYPE_p_unsigned_char colorbuf) {
    long cPtr = exampleJNI.heatmap_render_saturated_to(heatmap_t.getCPtr(h), h, heatmap_colorscheme_t.getCPtr(colorscheme), colorscheme, saturation, SWIGTYPE_p_unsigned_char.getCPtr(colorbuf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static heatmap_stamp_t heatmap_stamp_load(long w, long h, SWIGTYPE_p_float data) {
    long cPtr = exampleJNI.heatmap_stamp_load(w, h, SWIGTYPE_p_float.getCPtr(data));
    return (cPtr == 0) ? null : new heatmap_stamp_t(cPtr, false);
  }

  public static heatmap_stamp_t heatmap_stamp_gen(long radius) {
    long cPtr = exampleJNI.heatmap_stamp_gen(radius);
    return (cPtr == 0) ? null : new heatmap_stamp_t(cPtr, false);
  }

  public static heatmap_stamp_t heatmap_stamp_gen_nonlinear(long radius, SWIGTYPE_p_f_float__float distshape) {
    long cPtr = exampleJNI.heatmap_stamp_gen_nonlinear(radius, SWIGTYPE_p_f_float__float.getCPtr(distshape));
    return (cPtr == 0) ? null : new heatmap_stamp_t(cPtr, false);
  }

  public static void heatmap_stamp_free(heatmap_stamp_t s) {
    exampleJNI.heatmap_stamp_free(heatmap_stamp_t.getCPtr(s), s);
  }

  public static heatmap_colorscheme_t heatmap_colorscheme_load(SWIGTYPE_p_unsigned_char colors, long ncolors) {
    long cPtr = exampleJNI.heatmap_colorscheme_load(SWIGTYPE_p_unsigned_char.getCPtr(colors), ncolors);
    return (cPtr == 0) ? null : new heatmap_colorscheme_t(cPtr, false);
  }

  public static void heatmap_colorscheme_free(heatmap_colorscheme_t cs) {
    exampleJNI.heatmap_colorscheme_free(heatmap_colorscheme_t.getCPtr(cs), cs);
  }

  public static void setHeatmap_cs_default(heatmap_colorscheme_t value) {
    exampleJNI.heatmap_cs_default_set(heatmap_colorscheme_t.getCPtr(value), value);
  }

  public static heatmap_colorscheme_t getHeatmap_cs_default() {
    long cPtr = exampleJNI.heatmap_cs_default_get();
    return (cPtr == 0) ? null : new heatmap_colorscheme_t(cPtr, false);
  }

}
