/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.adsamcik.signalcollector.map;

public class exampleJNI {
  public final static native void heatmap_t_buf_set(long jarg1, heatmap_t jarg1_, long jarg2);
  public final static native long heatmap_t_buf_get(long jarg1, heatmap_t jarg1_);
  public final static native void heatmap_t_max_set(long jarg1, heatmap_t jarg1_, float jarg2);
  public final static native float heatmap_t_max_get(long jarg1, heatmap_t jarg1_);
  public final static native void heatmap_t_w_set(long jarg1, heatmap_t jarg1_, long jarg2);
  public final static native long heatmap_t_w_get(long jarg1, heatmap_t jarg1_);
  public final static native void heatmap_t_h_set(long jarg1, heatmap_t jarg1_, long jarg2);
  public final static native long heatmap_t_h_get(long jarg1, heatmap_t jarg1_);
  public final static native long new_heatmap_t();
  public final static native void delete_heatmap_t(long jarg1);
  public final static native void heatmap_stamp_t_buf_set(long jarg1, heatmap_stamp_t jarg1_, long jarg2);
  public final static native long heatmap_stamp_t_buf_get(long jarg1, heatmap_stamp_t jarg1_);
  public final static native void heatmap_stamp_t_w_set(long jarg1, heatmap_stamp_t jarg1_, long jarg2);
  public final static native long heatmap_stamp_t_w_get(long jarg1, heatmap_stamp_t jarg1_);
  public final static native void heatmap_stamp_t_h_set(long jarg1, heatmap_stamp_t jarg1_, long jarg2);
  public final static native long heatmap_stamp_t_h_get(long jarg1, heatmap_stamp_t jarg1_);
  public final static native long new_heatmap_stamp_t();
  public final static native void delete_heatmap_stamp_t(long jarg1);
  public final static native void heatmap_colorscheme_t_colors_set(long jarg1, heatmap_colorscheme_t jarg1_, long jarg2);
  public final static native long heatmap_colorscheme_t_colors_get(long jarg1, heatmap_colorscheme_t jarg1_);
  public final static native void heatmap_colorscheme_t_ncolors_set(long jarg1, heatmap_colorscheme_t jarg1_, long jarg2);
  public final static native long heatmap_colorscheme_t_ncolors_get(long jarg1, heatmap_colorscheme_t jarg1_);
  public final static native long new_heatmap_colorscheme_t();
  public final static native void delete_heatmap_colorscheme_t(long jarg1);
  public final static native long heatmap_new(long jarg1, long jarg2);
  public final static native void heatmap_free(long jarg1, heatmap_t jarg1_);
  public final static native void heatmap_add_point(long jarg1, heatmap_t jarg1_, long jarg2, long jarg3);
  public final static native void heatmap_add_point_with_stamp(long jarg1, heatmap_t jarg1_, long jarg2, long jarg3, long jarg4, heatmap_stamp_t jarg4_);
  public final static native void heatmap_add_weighted_point(long jarg1, heatmap_t jarg1_, long jarg2, long jarg3, float jarg4);
  public final static native void heatmap_add_weighted_point_with_stamp(long jarg1, heatmap_t jarg1_, long jarg2, long jarg3, float jarg4, long jarg5, heatmap_stamp_t jarg5_);
  public final static native long heatmap_render_default_to(long jarg1, heatmap_t jarg1_, long jarg2);
  public final static native long heatmap_render_to(long jarg1, heatmap_t jarg1_, long jarg2, heatmap_colorscheme_t jarg2_, long jarg3);
  public final static native long heatmap_render_saturated_to(long jarg1, heatmap_t jarg1_, long jarg2, heatmap_colorscheme_t jarg2_, float jarg3, long jarg4);
  public final static native long heatmap_stamp_load(long jarg1, long jarg2, long jarg3);
  public final static native long heatmap_stamp_gen(long jarg1);
  public final static native long heatmap_stamp_gen_nonlinear(long jarg1, long jarg2);
  public final static native void heatmap_stamp_free(long jarg1, heatmap_stamp_t jarg1_);
  public final static native long heatmap_colorscheme_load(long jarg1, long jarg2);
  public final static native void heatmap_colorscheme_free(long jarg1, heatmap_colorscheme_t jarg1_);
  public final static native void heatmap_cs_default_set(long jarg1, heatmap_colorscheme_t jarg1_);
  public final static native long heatmap_cs_default_get();
}
