/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.adsamcik.signalcollector.map;

public class heatmap_colorscheme_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected heatmap_colorscheme_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(heatmap_colorscheme_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_heatmap_colorscheme_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColors(SWIGTYPE_p_unsigned_char value) {
    exampleJNI.heatmap_colorscheme_t_colors_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getColors() {
    long cPtr = exampleJNI.heatmap_colorscheme_t_colors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setNcolors(long value) {
    exampleJNI.heatmap_colorscheme_t_ncolors_set(swigCPtr, this, value);
  }

  public long getNcolors() {
    return exampleJNI.heatmap_colorscheme_t_ncolors_get(swigCPtr, this);
  }

  public heatmap_colorscheme_t() {
    this(exampleJNI.new_heatmap_colorscheme_t(), true);
  }

}
