/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 #include "heatmap.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1buf_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  float *arg2 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  if (arg1) (arg1)->buf = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1buf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  result = (float *) ((arg1)->buf);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1max_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->max = arg2;
}


SWIGEXPORT jfloat JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1max_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  result = (float) ((arg1)->max);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1w_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->w = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1w_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  result = (unsigned int) ((arg1)->w);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1h_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->h = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1t_1h_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  result = (unsigned int) ((arg1)->h);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_new_1heatmap_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  heatmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (heatmap_t *)calloc(1, sizeof(heatmap_t));
  *(heatmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_delete_1heatmap_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(heatmap_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1buf_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  float *arg2 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  if (arg1) (arg1)->buf = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1buf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  result = (float *) ((arg1)->buf);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1w_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->w = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1w_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  result = (unsigned int) ((arg1)->w);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1h_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->h = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1t_1h_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  result = (unsigned int) ((arg1)->h);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_new_1heatmap_1stamp_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  heatmap_stamp_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (heatmap_stamp_t *)calloc(1, sizeof(heatmap_stamp_t));
  *(heatmap_stamp_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_delete_1heatmap_1stamp_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1t_1colors_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  if (arg1) (arg1)->colors = (unsigned char const *)arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1t_1colors_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  result = (unsigned char *) ((arg1)->colors);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1t_1ncolors_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->ncolors = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1t_1ncolors_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  result =  ((arg1)->ncolors);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_new_1heatmap_1colorscheme_1t(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  heatmap_colorscheme_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (heatmap_colorscheme_t *)calloc(1, sizeof(heatmap_colorscheme_t));
  *(heatmap_colorscheme_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_delete_1heatmap_1colorscheme_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1new(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  heatmap_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (heatmap_t *)heatmap_new(arg1,arg2);
  *(heatmap_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  heatmap_free(arg1);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1add_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  heatmap_add_point(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1add_1point_1with_1stamp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jobject jarg4_) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  heatmap_stamp_t *arg4 = (heatmap_stamp_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  arg4 = *(heatmap_stamp_t **)&jarg4; 
  heatmap_add_point_with_stamp(arg1,arg2,arg3,(heatmap_stamp_t const *)arg4);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1add_1weighted_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jfloat jarg4) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  float arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  arg4 = (float)jarg4; 
  heatmap_add_weighted_point(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1add_1weighted_1point_1with_1stamp(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jfloat jarg4, jlong jarg5, jobject jarg5_) {
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned int arg2 ;
  unsigned int arg3 ;
  float arg4 ;
  heatmap_stamp_t *arg5 = (heatmap_stamp_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg5_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = (unsigned int)jarg3; 
  arg4 = (float)jarg4; 
  arg5 = *(heatmap_stamp_t **)&jarg5; 
  heatmap_add_weighted_point_with_stamp(arg1,arg2,arg3,arg4,(heatmap_stamp_t const *)arg5);
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1render_1default_1to(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  result = (unsigned char *)heatmap_render_default_to((heatmap_t const *)arg1,arg2);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1render_1to(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jlong jarg3) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  heatmap_colorscheme_t *arg2 = (heatmap_colorscheme_t *) 0 ;
  unsigned char *arg3 = (unsigned char *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = *(heatmap_colorscheme_t **)&jarg2; 
  arg3 = *(unsigned char **)&jarg3; 
  result = (unsigned char *)heatmap_render_to((heatmap_t const *)arg1,(heatmap_colorscheme_t const *)arg2,arg3);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1render_1saturated_1to(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jfloat jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  heatmap_t *arg1 = (heatmap_t *) 0 ;
  heatmap_colorscheme_t *arg2 = (heatmap_colorscheme_t *) 0 ;
  float arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(heatmap_t **)&jarg1; 
  arg2 = *(heatmap_colorscheme_t **)&jarg2; 
  arg3 = (float)jarg3; 
  arg4 = *(unsigned char **)&jarg4; 
  result = (unsigned char *)heatmap_render_saturated_to((heatmap_t const *)arg1,(heatmap_colorscheme_t const *)arg2,arg3,arg4);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1load(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  unsigned int arg2 ;
  float *arg3 = (float *) 0 ;
  heatmap_stamp_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = *(float **)&jarg3; 
  result = (heatmap_stamp_t *)heatmap_stamp_load(arg1,arg2,arg3);
  *(heatmap_stamp_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1gen(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  heatmap_stamp_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  result = (heatmap_stamp_t *)heatmap_stamp_gen(arg1);
  *(heatmap_stamp_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1gen_1nonlinear(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  unsigned int arg1 ;
  float (*arg2)(float) = (float (*)(float)) 0 ;
  heatmap_stamp_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  arg2 = *(float (**)(float))&jarg2; 
  result = (heatmap_stamp_t *)heatmap_stamp_gen_nonlinear(arg1,arg2);
  *(heatmap_stamp_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1stamp_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  heatmap_stamp_t *arg1 = (heatmap_stamp_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_stamp_t **)&jarg1; 
  heatmap_stamp_free(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1load(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  size_t arg2 ;
  heatmap_colorscheme_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (size_t)jarg2; 
  result = (heatmap_colorscheme_t *)heatmap_colorscheme_load((unsigned char const *)arg1,arg2);
  *(heatmap_colorscheme_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1colorscheme_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  heatmap_colorscheme_free(arg1);
}


SWIGEXPORT void JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1cs_1default_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  heatmap_colorscheme_t *arg1 = (heatmap_colorscheme_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(heatmap_colorscheme_t **)&jarg1; 
  heatmap_cs_default = (heatmap_colorscheme_t const *)arg1;
}


SWIGEXPORT jlong JNICALL Java_com_adsamcik_signalcollector_map_exampleJNI_heatmap_1cs_1default_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  heatmap_colorscheme_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (heatmap_colorscheme_t *)heatmap_cs_default;
  *(heatmap_colorscheme_t **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

