package com.adsamcik.tracker.impexp.importer.file

import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteConstraintException
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteStatement
import com.adsamcik.tracker.impexp.importer.FileImportStream
import com.adsamcik.tracker.impexp.importer.ImportResult
import com.adsamcik.tracker.logger.Reporter
import com.adsamcik.tracker.shared.base.database.AppDatabase
import io.requery.android.database.sqlite.SQLiteDatabase
import java.io.File

/**
 * Merges compatible rows from a database file into the current database.
 *
 * The source stream is copied to a private working file. Auto-generated integer primary keys are
 * shifted above the current target range and every referencing foreign key is shifted by the same
 * amount before rows are copied. The target merge is one transaction, so an unsupported constraint
 * or broken foreign key rolls back the complete database-file import.
 */
internal class DatabaseImport : FileImport {
	override val supportedExtensions: Collection<String> = listOf("db")
	override val transactionMode: ImportTransactionMode = ImportTransactionMode.IMPORTER_MANAGED

	override suspend fun import(
		context: Context,
		database: AppDatabase,
		stream: FileImportStream,
	): ImportResult {
		val databaseTmpFile = createImportTempFile(context)
		var fromDatabase: SQLiteDatabase? = null
		return try {
			databaseTmpFile.outputStream().use(stream::copyTo)
			fromDatabase = SQLiteDatabase.openDatabase(
				databaseTmpFile.path,
				null,
				SQLiteDatabase.OPEN_READWRITE,
			)
			importCopiedDatabase(fromDatabase, database)
		} finally {
			fromDatabase?.close()
			databaseTmpFile.delete()
		}
	}

	private fun createImportTempFile(context: Context): File {
		val importCacheDir = File(context.cacheDir, IMPORT_CACHE_DIR).apply { mkdirs() }
		return File.createTempFile("db-import-", ".db", importCacheDir)
	}

	internal fun importCopiedDatabase(
		from: SupportSQLiteDatabase,
		database: AppDatabase,
	): ImportResult {
		var result: DatabaseImportResult? = null
		return try {
			database.runInTransaction {
				val currentResult = importDatabase(from, database.openHelper.writableDatabase)
				if (currentResult is DatabaseImportResult.Failure) {
					throw DatabaseImportRollback(currentResult)
				}
				result = currentResult
			}
			(result as DatabaseImportResult.Success).result
		} catch (rollback: DatabaseImportRollback) {
			rollback.failure.toImportResult()
		}
	}

	internal fun importDatabase(
		from: SupportSQLiteDatabase,
		to: SupportSQLiteDatabase,
	): DatabaseImportResult {
		return try {
			val allSourceTables = from.getAllTables()
				.filterNot(::isSystemTable)
				.map { from.getTable(it) }
			val sourceTablesByName = allSourceTables.associateBy { it.tableName }
			val matchingTables = getMatchingTables(from, to)
				.map { tableName -> sourceTablesByName.getValue(tableName) to to.getTable(tableName) }
			val matchingTableNames = matchingTables.map { it.first.tableName }.toSet()
			val importableTables = matchingTables
				.filter { (source, target) -> target.canImport(source) }
				.toMutableList()
			do {
				val importableNames = importableTables.map { it.first.tableName }.toSet()
				val removed = importableTables.removeAll { (source, _) ->
					source.foreignKeys.any {
						it.parentTable in matchingTableNames && it.parentTable !in importableNames
					}
				}
			} while (removed)
			val tables = importableTables
				.sortedByTopology()

			from.beginTransaction()
			try {
				from.execSQL("PRAGMA defer_foreign_keys = ON")
				remapAutoGeneratedIds(from, to, tables, allSourceTables)
				findForeignKeyViolation(from)?.let {
					throw DatabaseImportPlanningException(
						DatabaseImportFailure.ForeignKeyViolation(it),
					)
				}
				from.setTransactionSuccessful()
			} finally {
				from.endTransaction()
			}

			var result = ImportResult.EMPTY
			for ((sourceTable, _) in tables) {
				when (val tableResult = importTable(from, to, sourceTable)) {
					is DatabaseImportResult.Success -> result += tableResult.result
					is DatabaseImportResult.Failure -> return tableResult
				}
			}

			findForeignKeyViolation(to)?.let {
				return DatabaseImportResult.Failure(
					DatabaseImportFailure.ForeignKeyViolation(it),
				)
			}
			DatabaseImportResult.Success(result)
		} catch (planning: DatabaseImportPlanningException) {
			DatabaseImportResult.Failure(planning.failure)
		} catch (constraint: SQLiteConstraintException) {
			Reporter.report(Exception("Constraint issue while importing database", constraint))
			DatabaseImportResult.Failure(
				DatabaseImportFailure.ConstraintViolation("database import"),
			)
		} catch (exception: Exception) {
			Reporter.report(Exception("Database import failed", exception))
			DatabaseImportResult.Failure(
				DatabaseImportFailure.Unexpected(exception.javaClass.simpleName),
			)
		}
	}

	private fun SupportSQLiteDatabase.getTable(tableName: String): ImportTable {
		val columns = query("PRAGMA table_info(${tableName.quoted()})").use { cursor ->
			buildList {
				while (cursor.moveToNext()) {
					val primaryKeyPosition = cursor.getInt(cursor.getColumnIndexOrThrow("pk"))
					add(
						ImportColumn(
							columnName = cursor.getString(cursor.getColumnIndexOrThrow("name")),
							isNotNull = cursor.getInt(cursor.getColumnIndexOrThrow("notnull")) != 0 ||
								primaryKeyPosition > 0,
							isUnique = false,
							type = cursor.getString(cursor.getColumnIndexOrThrow("type")).orEmpty(),
							defaultValue = cursor.getStringOrNull("dflt_value"),
							primaryKeyPosition = primaryKeyPosition,
						),
					)
				}
			}
		}
		val uniqueConstraints = getUniqueConstraints(tableName, columns)
		val foreignKeys = query("PRAGMA foreign_key_list(${tableName.quoted()})").use { cursor ->
			buildList {
				while (cursor.moveToNext()) {
					add(
						ImportForeignKey(
							childColumn = cursor.getString(cursor.getColumnIndexOrThrow("from")),
							parentTable = cursor.getString(cursor.getColumnIndexOrThrow("table")),
							parentColumn = cursor.getString(cursor.getColumnIndexOrThrow("to")),
						),
					)
				}
			}
		}
		val createSql = query(
			"SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?",
			arrayOf(tableName),
		).use { cursor ->
			if (cursor.moveToFirst()) cursor.getString(0).orEmpty() else ""
		}
		return ImportTable(
			tableName = tableName,
			columns = columns.map { column ->
				column.copy(
					isUnique = uniqueConstraints.any {
						it.size == 1 && it.single() == column.columnName
					},
				)
			},
			foreignKeys = foreignKeys,
			uniqueConstraints = uniqueConstraints,
			isAutoIncrement = createSql.contains("AUTOINCREMENT", ignoreCase = true),
		)
	}

	private fun SupportSQLiteDatabase.getUniqueConstraints(
		tableName: String,
		columns: List<ImportColumn>,
	): List<List<String>> {
		val primaryKey = columns
			.filter { it.primaryKeyPosition > 0 }
			.sortedBy { it.primaryKeyPosition }
			.map { it.columnName }
		val uniqueIndexNames = query("PRAGMA index_list(${tableName.quoted()})").use { cursor ->
			buildList {
				while (cursor.moveToNext()) {
					if (cursor.getInt(cursor.getColumnIndexOrThrow("unique")) != 0) {
						add(cursor.getString(cursor.getColumnIndexOrThrow("name")))
					}
				}
			}
		}
		return buildList {
			if (primaryKey.isNotEmpty()) add(primaryKey)
			uniqueIndexNames.forEach { indexName ->
				val indexColumns = query("PRAGMA index_info(${indexName.quoted()})").use { cursor ->
					buildList {
						while (cursor.moveToNext()) {
							add(cursor.getString(cursor.getColumnIndexOrThrow("name")))
						}
					}
				}
				if (indexColumns.isNotEmpty() && indexColumns !in this) add(indexColumns)
			}
		}
	}

	private fun SupportSQLiteDatabase.getAllTables(): List<String> {
		return query("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name").use {
			buildList {
				while (it.moveToNext()) add(it.getString(0))
			}
		}
	}

	private fun getMatchingTables(
		fromDatabase: SupportSQLiteDatabase,
		toDatabase: SupportSQLiteDatabase,
	): List<String> {
		val targetTables = toDatabase.getAllTables().toSet()
		return fromDatabase.getAllTables().filter {
			!isSystemTable(it) && it in targetTables
		}
	}

	private fun isSystemTable(tableName: String): Boolean {
		return tableName.startsWith("sqlite_") || tableName in SYSTEM_TABLES
	}

	private fun List<Pair<ImportTable, ImportTable>>.sortedByTopology():
			List<Pair<ImportTable, ImportTable>> {
		val byName = associateBy { it.first.tableName }
		val remaining = associate { pair ->
			pair.first.tableName to pair.first.foreignKeys
				.map { it.parentTable }
				.filter { it != pair.first.tableName && it in byName }
				.toMutableSet()
		}.toMutableMap()
		val sorted = mutableListOf<Pair<ImportTable, ImportTable>>()

		while (remaining.isNotEmpty()) {
			val ready = remaining
				.filterValues { it.isEmpty() }
				.keys
				.sorted()
			if (ready.isEmpty()) {
				throw DatabaseImportPlanningException(DatabaseImportFailure.CyclicForeignKeys)
			}
			ready.forEach { tableName ->
				sorted += byName.getValue(tableName)
				remaining.remove(tableName)
				remaining.values.forEach { it.remove(tableName) }
			}
		}
		return sorted
	}

	private fun remapAutoGeneratedIds(
		from: SupportSQLiteDatabase,
		to: SupportSQLiteDatabase,
		tables: List<Pair<ImportTable, ImportTable>>,
		allSourceTables: List<ImportTable>,
	) {
		val shiftedKeys = mutableMapOf<Pair<String, String>, Long>()
		tables.forEach { (source, target) ->
			val primaryKey = source.primaryKey
			if (!source.isAutoIncrement || primaryKey.size != 1) return@forEach
			val sourceColumn = source.column(primaryKey.single()) ?: return@forEach
			val targetColumn = target.column(primaryKey.single()) ?: return@forEach
			if (!sourceColumn.isInteger || !targetColumn.isInteger) return@forEach

			val sourceRange = from.readRange(source.tableName, sourceColumn.columnName)
				?: return@forEach
			val targetMaximum = to.readMaximum(target.tableName, targetColumn.columnName)
				?: return@forEach
			if (sourceRange.first > targetMaximum) return@forEach

			val offset = try {
				Math.addExact(Math.subtractExact(targetMaximum, sourceRange.first), 1L)
			} catch (_: ArithmeticException) {
				throw DatabaseImportPlanningException(
					DatabaseImportFailure.IdRangeOverflow(source.tableName),
				)
			}
			try {
				Math.addExact(sourceRange.last, offset)
			} catch (_: ArithmeticException) {
				throw DatabaseImportPlanningException(
					DatabaseImportFailure.IdRangeOverflow(source.tableName),
				)
			}
			shiftedKeys[source.tableName to sourceColumn.columnName] = offset
		}

		val columnShifts = mutableMapOf<String, MutableMap<String, Long>>()
		fun addShift(table: String, column: String, offset: Long) {
			val shifts = columnShifts.getOrPut(table) { mutableMapOf() }
			val existing = shifts[column]
			if (existing != null && existing != offset) {
				throw DatabaseImportPlanningException(
					DatabaseImportFailure.ConflictingForeignKeyRemap(table, column),
				)
			}
			shifts[column] = offset
		}

		shiftedKeys.forEach { (key, offset) -> addShift(key.first, key.second, offset) }
		allSourceTables.forEach { source ->
			source.foreignKeys.forEach { foreignKey ->
				shiftedKeys[foreignKey.parentTable to foreignKey.parentColumn]?.let { offset ->
					addShift(source.tableName, foreignKey.childColumn, offset)
				}
			}
		}

		val sourceTables = allSourceTables.associateBy { it.tableName }
		columnShifts.forEach { (tableName, shifts) ->
			val table = sourceTables.getValue(tableName)
			shifts.forEach { (columnName, offset) ->
				if (table.uniqueConstraints.any { columnName in it }) {
					from.shiftUniqueColumn(tableName, columnName, offset)
				} else {
					from.execSQL(
						"UPDATE ${tableName.quoted()} " +
							"SET ${columnName.quoted()} = ${columnName.quoted()} + ? " +
							"WHERE ${columnName.quoted()} IS NOT NULL",
						arrayOf(offset),
					)
				}
			}
		}
	}

	private fun SupportSQLiteDatabase.shiftUniqueColumn(
		tableName: String,
		columnName: String,
		offset: Long,
	) {
		val originalValues = query(
			"SELECT DISTINCT ${columnName.quoted()} FROM ${tableName.quoted()} " +
				"WHERE ${columnName.quoted()} IS NOT NULL ORDER BY ${columnName.quoted()} DESC",
		).use { cursor ->
			buildList {
				while (cursor.moveToNext()) add(cursor.getLong(0))
			}
		}
		val statement = compileStatement(
			"UPDATE ${tableName.quoted()} " +
				"SET ${columnName.quoted()} = ${columnName.quoted()} + ? " +
				"WHERE ${columnName.quoted()} = ?",
		)
		try {
			originalValues.forEach { original ->
				statement.clearBindings()
				statement.bindLong(1, offset)
				statement.bindLong(2, original)
				statement.executeUpdateDelete()
			}
		} finally {
			statement.close()
		}
	}

	private fun SupportSQLiteDatabase.readRange(
		tableName: String,
		columnName: String,
	): LongRange? {
		return query(
			"SELECT MIN(${columnName.quoted()}), MAX(${columnName.quoted()}) " +
				"FROM ${tableName.quoted()}",
		).use { cursor ->
			if (!cursor.moveToFirst() || cursor.isNull(0)) null
			else cursor.getLong(0)..cursor.getLong(1)
		}
	}

	private fun SupportSQLiteDatabase.readMaximum(
		tableName: String,
		columnName: String,
	): Long? {
		return query(
			"SELECT MAX(${columnName.quoted()}) FROM ${tableName.quoted()}",
		).use { cursor ->
			if (!cursor.moveToFirst() || cursor.isNull(0)) null else cursor.getLong(0)
		}
	}

	private fun importTable(
		from: SupportSQLiteDatabase,
		to: SupportSQLiteDatabase,
		table: ImportTable,
	): DatabaseImportResult {
		val targetColumns = to.getTable(table.tableName).columns.map { it.columnName }.toSet()
		val matchingColumns = table.columns.filter { it.columnName in targetColumns }
		if (matchingColumns.isEmpty()) return DatabaseImportResult.Success(ImportResult.EMPTY)

		val columnsSql = matchingColumns.joinToString { it.columnName.quoted() }
		val placeholders = List(matchingColumns.size) { "?" }.joinToString()
		val statement = to.compileStatement(
			"INSERT OR IGNORE INTO ${table.tableName.quoted()} ($columnsSql) VALUES ($placeholders)",
		)
		var success = 0
		var skipped = 0

		return try {
			from.query(
				"SELECT $columnsSql FROM ${table.tableName.quoted()}",
			).use { cursor ->
				while (cursor.moveToNext()) {
					statement.clearBindings()
					cursor.bindRow(statement)
					if (statement.executeInsert() == -1L) skipped++ else success++
				}
			}
			DatabaseImportResult.Success(
				ImportResult(successCount = success, skippedCount = skipped),
			)
		} catch (constraint: SQLiteConstraintException) {
			Reporter.report(
				Exception("Constraint issue while importing table ${table.tableName}", constraint),
			)
			DatabaseImportResult.Failure(
				DatabaseImportFailure.ConstraintViolation(table.tableName),
			)
		} finally {
			statement.close()
		}
	}

	private fun Cursor.bindRow(statement: SupportSQLiteStatement) {
		for (index in 0 until columnCount) {
			val bindIndex = index + 1
			when (getType(index)) {
				Cursor.FIELD_TYPE_NULL -> statement.bindNull(bindIndex)
				Cursor.FIELD_TYPE_INTEGER -> statement.bindLong(bindIndex, getLong(index))
				Cursor.FIELD_TYPE_FLOAT -> statement.bindDouble(bindIndex, getDouble(index))
				Cursor.FIELD_TYPE_STRING -> statement.bindString(bindIndex, getString(index))
				Cursor.FIELD_TYPE_BLOB -> statement.bindBlob(bindIndex, getBlob(index))
			}
		}
	}

	private fun findForeignKeyViolation(database: SupportSQLiteDatabase): String? {
		database.query("PRAGMA foreign_key_check").use { cursor ->
			if (cursor.moveToFirst()) return cursor.getString(0)
		}
		return null
	}

	private fun Cursor.getStringOrNull(columnName: String): String? {
		val index = getColumnIndexOrThrow(columnName)
		return if (isNull(index)) null else getString(index)
	}

	private fun String.quoted(): String = "`${replace("`", "``")}`"

	internal companion object {
		const val IMPORT_MODE = "COPY_LOCK_REMAP_TRANSACTION"
		private const val IMPORT_CACHE_DIR = "database-import"
		private val SYSTEM_TABLES = setOf("room_master_table", "android_metadata")
	}
}

internal sealed interface DatabaseImportResult {
	data class Success(val result: ImportResult) : DatabaseImportResult
	data class Failure(val reason: DatabaseImportFailure) : DatabaseImportResult {
		fun toImportResult(): ImportResult = ImportResult(
			failedCount = 1,
			errors = listOf(reason.message),
		)
	}
}

internal sealed interface DatabaseImportFailure {
	val message: String

	data class ConstraintViolation(val tableName: String) : DatabaseImportFailure {
		override val message: String = "Constraint violation in table $tableName"
	}

	data class ForeignKeyViolation(val tableName: String) : DatabaseImportFailure {
		override val message: String = "Foreign key violation in table $tableName"
	}

	data class IdRangeOverflow(val tableName: String) : DatabaseImportFailure {
		override val message: String = "Cannot safely remap IDs in table $tableName"
	}

	data class ConflictingForeignKeyRemap(
		val tableName: String,
		val columnName: String,
	) : DatabaseImportFailure {
		override val message: String =
			"Cannot consistently remap $tableName.$columnName"
	}

	data object CyclicForeignKeys : DatabaseImportFailure {
		override val message: String = "Database contains cyclic foreign-key dependencies"
	}

	data class Unexpected(val causeType: String) : DatabaseImportFailure {
		override val message: String = "Unexpected database import failure ($causeType)"
	}
}

private class DatabaseImportRollback(
	val failure: DatabaseImportResult.Failure,
) : RuntimeException()

private class DatabaseImportPlanningException(
	val failure: DatabaseImportFailure,
) : RuntimeException()

internal data class ImportTable(
	val tableName: String,
	val columns: List<ImportColumn>,
	val foreignKeys: List<ImportForeignKey> = emptyList(),
	val uniqueConstraints: List<List<String>> = emptyList(),
	val isAutoIncrement: Boolean = false,
) {
	val primaryKey: List<String>
		get() = columns
			.filter { it.primaryKeyPosition > 0 }
			.sortedBy { it.primaryKeyPosition }
			.map { it.columnName }

	fun column(name: String): ImportColumn? = columns.find { it.columnName == name }

	fun canImport(source: ImportTable): Boolean {
		val sourceColumns = source.columns.map { it.columnName }.toSet()
		return columns.none { targetColumn ->
			targetColumn.isNotNull &&
				targetColumn.defaultValue == null &&
				targetColumn.columnName !in sourceColumns &&
				!(isAutoIncrement && targetColumn.columnName in primaryKey)
		}
	}

	override fun equals(other: Any?): Boolean =
		this === other || other is ImportTable && tableName == other.tableName

	override fun hashCode(): Int = tableName.hashCode()
}

internal data class ImportColumn(
	val columnName: String,
	val isNotNull: Boolean,
	val isUnique: Boolean,
	val type: String = "",
	val defaultValue: String? = null,
	val primaryKeyPosition: Int = 0,
) {
	val isInteger: Boolean get() = type.contains("INT", ignoreCase = true)

	override fun equals(other: Any?): Boolean =
		this === other || other is ImportColumn && columnName == other.columnName

	override fun hashCode(): Int = columnName.hashCode()
}

internal data class ImportForeignKey(
	val childColumn: String,
	val parentTable: String,
	val parentColumn: String,
)
